env:
  global:
      - REPO_DIR="marisa-trie"
      - BUILD_COMMIT=0.7.4
      - BUILD_DEPENDS=""
      - TEST_DEPENDS="pytest hypothesis==2.0.0"
      - PLAT=x86_64
      - UNICODE_WIDTH=32

language: python
# Default Python version is usually 2.7
python: 3.5
sudo: required
dist: trusty
services: docker

matrix:
  exclude:
      # Exclude the default Python 3.5 build
      - python: 3.5
  include:
    - os: osx
      language: generic
      env:
        - MB_PYTHON_VERSION=2.7
    - os: osx
      language: generic
      env:
        - MB_PYTHON_VERSION=3.5
    - os: osx
      language: generic
      env:
        - MB_PYTHON_VERSION=3.6

before_install:
    - source multibuild/common_utils.sh
    - source multibuild/travis_steps.sh
    - before_install

install:
    # Maybe get and clean and patch source
    - clean_code $REPO_DIR $BUILD_COMMIT
    - build_wheel $REPO_DIR $PLAT

script:
    - install_run $PLAT

deploy:
  provider: s3
  region: "eu-west-1"
  access_key_id: "$ARTIFACTS_KEY"
  secret_access_key: "$ARTIFACTS_SECRET"
  bucket: "$ARTIFACTS_BUCKET"
  skip_cleanup: true
  local_dir: wheelhouse/
