env:
  global:
      - REPO_DIR="marisa-trie"
      - BUILD_COMMIT=0.7.4
      - BUILD_DEPENDS=""
      - TEST_DEPENDS="pytest hypothesis==2.0.0"
      - PLAT=x86_64
      - UNICODE_WIDTH=32

language: python
# Default Python version is usually 2.7
python: 3.5
sudo: required
dist: trusty
services: docker

matrix:
  exclude:
      # Exclude the default Python 3.5 build
      - python: 3.5
  include:
    - os: linux
      env:
        - MB_PYTHON_VERSION=2.7
    - os: linux
      env:
        - MB_PYTHON_VERSION=3.4
    - os: linux
      env:
        - MB_PYTHON_VERSION=3.5
    - os: linux
      env:
        - MB_PYTHON_VERSION=3.6
    - os: osx
      language: generic
      env:
        - MB_PYTHON_VERSION=2.7
    - os: osx
      language: generic
      env:
        - MB_PYTHON_VERSION=3.5
    - os: osx
      language: generic
      env:
        - MB_PYTHON_VERSION=3.6

before_install:
    - source multibuild/common_utils.sh
    - source multibuild/travis_steps.sh
    - before_install

install:
    # Maybe get and clean and patch source
    - clean_code $REPO_DIR $BUILD_COMMIT
    - build_wheel $REPO_DIR $PLAT

script:
    - install_run $PLAT

deploy:
  provider: releases
  api_key:
    secure: gLATMibFS1A+Mk/bj9l5hA8Dm7jxpWHhg6R3Y1PNIjCt/RpE2IzWi0J4jLjIjaASuRwoG5PqsB0fk3/op3vFJCvhEDh/nOxqo5N5cenWJDaVWdIOljHIO3loA8qbl08oWgjJuFmyZgPgazgYbXNcKsAi1LOiudwAqV2fQ4BBb6N8h+n0iQw9S3IpJ7wo+pySZI61slrfbHlC0W+O+rqQ3jdohzC6R3DPCCZBhZoB7f5PFnAYjdVdbtEp2qQyndEIhBigPzA6vbQY5wh7XxZh6wDi7jXiwTcqeoUxJ1oMdlVGnqvuVL2Q9iOC+sMWAMvpMBY+JDw7frNPKBgf7eqLo3aJsgmHUshR7OsjWwIQZGz5EvBTEGeTBHQLAosdv7w2tj7UeGm6ppdUc1HScpX8/qAzFIP2KL0ieBdo7w2fsg3yiG7mRRuRGeFj+laqPKmNbRczperBRR+EgW/vZpMyfKaunYGVPSQmSsrZBma5zYtI6sfITzXB0Knjchs313olhdQqFvNalZfkEzOPH7WjCE5ajCP9ogMuXMDjYTk8EmxAKTe52LgX8X4jJI6C28wmUkBCBAyNZMr1xASswzEIOwbgMzUXAThQTumswggUgx+XPv85mzYwIPBFgwa7cQr2vQvY46DtO0zKXFwdjSBAx0+uLPRWznJFCs1jMDlbjdE=
  file: "*.whl"
  on:
    repo: superbobry/marisa-trie-wheels
